#!/bin/sh

DOTFILES_HOME="$( cd "$( dirname "$0" )" && pwd )"

# if [ -f ~/.vimrc ]; then mv ~/.bashrc ~/bashrc.backup; fi
# if [ -f ~/.vimrc ]; then mv ~/.vimrc ~/vimrc.backup; fi

touch "${HOME}/.bashrc-local"

echo "export DOTFILES_HOME='$DOTFILES_HOME'" > ~/.bashrc
cat $DOTFILES_HOME/bashrc >> ~/.bashrc

ln -s -f $DOTFILES_HOME/vimrc ~/.vimrc
ln -s -f $DOTFILES_HOME/.gitignore ~/.gitignore

git config --global core.excludesfile '~/.gitignore'

echo "Run '. ~/.bashrc' to update the changes."
